Fix bug in the update of records with custom primary_keys
The previous code would result in this error:
NoMethodError Exception: undefined method `find_all_by_id' for #<Class...